from pydantic import BaseModel, Field
class Signal(BaseModel):
    """
    Represents a trading signal generated by the AI.
    """
    action: str = Field(
        ...,
        description="The action to take, such as 'BUY', 'SELL', or 'HOLD'.",
    )
    opinion: float = Field(
        ...,
        description="Enter or Don't Enter. Should be either 'ENTER' or 'DON'T ENTER'.",
    )
    reason: str = Field(
        ...,
        description="The reason for the action, explaining why this signal was generated.",
    )
    summary: str = Field(
        ...,
        description="A summary of the analysis, including key indicators and their values.",
    )